### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by adrian1906** [PacktPublishing/-Learning-C-8-and-.NET-Core-3.0#1]
I do not see the Right_Side.jpg image (and others) as mentioned in the Packt Video. (Lesson 2_1)

**Comment by brantleybrn** [comment]
![Right Side](https://user-images.githubusercontent.com/42474948/58642334-60bc6c80-82ba-11e9-9f3d-c70553bff982.jpg)
![Front](https://user-images.githubusercontent.com/42474948/58642349-6914a780-82ba-11e9-9e99-410db09c1aab.jpg)
![ice-Front](https://user-images.githubusercontent.com/42474948/58642359-6fa31f00-82ba-11e9-9fa2-ca321426216f.jpg)

Very sorry for the wait on this... I wasn't alerted from Github like it usually does. Here are all the files from Section 2.
I will also make sure they get attached here to the Github like I thought I had done.

Again, sorry for the wait

Brantley
